name: "Add webMethods Helm repository action"

runs:
  using: "composite"
  steps:
    - name: Add webMethods Helm repository
      shell: bash
      run: |
        helm repo add webMethods https://charts.webmethods.io
        helm repo update
